apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: my-java-app
build:
  artifacts:
  - image: my-java-app-image

    custom:
      buildCommand: ./scripts/build.sh
manifests:
  rawYaml:
    - ./k8s/deployment.yaml

portForward:
- resourceType: deployment
  resourceName: my-java-app
  port: 8080
  localPort: 8080

# profiles:
# - name: debug
#   build:
#     artifacts:
#     - image: my-java-app-image
#       custom:
#         buildCommand: ./build.sh
#   deploy:
#     kubectl:
#       manifests:
#       - ./deployment.yaml
#   portForward:
#   - resourceType: deployment
#     resourceName: my-java-app
#     port: 8080
#     localPort: 8080
#   - resourceType: deployment
#     resourceName: my-java-app
#     port: 5005
#     localPort: 5005

